# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

users = User.create([
  { name: 'Andy Wolf', email: 'aw@gmail.com', password: 'password'},
  { name: 'Billy Jean', email: 'bj@gmail.com', password: 'password'}
])

students = Student.create([
  { name: 'Bobby Lam', stage: 'early', user_id: 1},
  { name: 'John Vega', stage: 'middle', user_id: 1},
  { name: 'Sue Wicks', stage: 'late', user_id: 2},
  { name: 'Cam Newton', stage: 'early', user_id: 2}
])

phonemes = Phoneme.create([
  { characters: "b" , classification: "beg"}, 
  { characters: "c" , classification: "beg"}, 
  { characters: "ch" , classification: "beg"}, 
  { characters: "d" , classification: "beg"}, 
  { characters: "f" , classification: "beg"}, 
  { characters: "g" , classification: "beg"}, 
  { characters: "h" , classification: "beg"}, 
  { characters: "j" , classification: "beg"}, 
  { characters: "k" , classification: "beg"}, 
  { characters: "l" , classification: "beg"}, 
  { characters: "m" , classification: "beg"}, 
  { characters: "n" , classification: "beg"}, 
  { characters: "p" , classification: "beg"}, 
  { characters: "qu" , classification: "beg"}, 
  { characters: "r" , classification: "beg"}, 
  { characters: "s" , classification: "beg"}, 
  { characters: "sh" , classification: "beg"}, 
  { characters: "t" , classification: "beg"}, 
  { characters: "th" , classification: "beg"}, 
  { characters: "v" , classification: "beg"}, 
  { characters: "w" , classification: "beg"}, 
  { characters: "wh" , classification: "beg"}, 
  { characters: "y" , classification: "beg"}, 
  { characters: "z" , classification: "beg"}, 
  { characters: "b" , classification: "beg"}, 
  { characters: "b" , classification: "beg"}, 
  { characters: "a" , classification: "mid"}, 
  { characters: "e" , classification: "mid"}, 
  { characters: "i" , classification: "mid"}, 
  { characters: "o" , classification: "mid"}, 
  { characters: "u" , classification: "mid"}, 
  { characters: "ai" , classification: "mid"}, 
  { characters: "ea" , classification: "mid"}, 
  { characters: "ee" , classification: "mid"}, 
  { characters: "oa" , classification: "mid"}, 
  { characters: "oo" , classification: "mid"}, 
  { characters: "b" , classification: "end"}, 
  { characters: "ck" , classification: "end"}, 
  { characters: "d" , classification: "end"}, 
  { characters: "ff" , classification: "end"}, 
  { characters: "g" , classification: "end"}, 
  { characters: "ll" , classification: "end"}, 
  { characters: "m" , classification: "end"}, 
  { characters: "n" , classification: "end"}, 
  { characters: "p" , classification: "end"}, 
  { characters: "ss" , classification: "end"}, 
  { characters: "t" , classification: "end"}, 
  { characters: "w" , classification: "end"}, 
  { characters: "x" , classification: "end"}, 
  { characters: "zz" , classification: "end"} 
])

student_phonemes = StudentPhoneme.create([
  { student_id: 1, phoneme_id: 1 },
  { student_id: 1, phoneme_id: 2 },
  { student_id: 1, phoneme_id: 3 },
  { student_id: 1, phoneme_id: 4 },
  { student_id: 1, phoneme_id: 5 },
  { student_id: 1, phoneme_id: 6 },
  { student_id: 1, phoneme_id: 7 },
  { student_id: 1, phoneme_id: 8 },
  { student_id: 1, phoneme_id: 9 },
  { student_id: 1, phoneme_id: 10 },
  { student_id: 1, phoneme_id: 11 },
  { student_id: 1, phoneme_id: 12 },
  { student_id: 1, phoneme_id: 13 },
  { student_id: 1, phoneme_id: 14 },
  { student_id: 1, phoneme_id: 15 },
  { student_id: 1, phoneme_id: 16 },
  { student_id: 1, phoneme_id: 17 },
  { student_id: 1, phoneme_id: 18 },
  { student_id: 1, phoneme_id: 19 },
  { student_id: 1, phoneme_id: 20 },
  { student_id: 1, phoneme_id: 21 },
  { student_id: 1, phoneme_id: 22 },
  { student_id: 1, phoneme_id: 23},
  { student_id: 1, phoneme_id: 24},
  { student_id: 1, phoneme_id: 25},
  { student_id: 1, phoneme_id: 26},
  { student_id: 1, phoneme_id: 27},
  { student_id: 1, phoneme_id: 28},
  { student_id: 1, phoneme_id: 29},
  { student_id: 1, phoneme_id: 30},
  { student_id: 1, phoneme_id: 31},
  { student_id: 1, phoneme_id: 32},
  { student_id: 1, phoneme_id: 33},
  { student_id: 1, phoneme_id: 34},
  { student_id: 1, phoneme_id: 35},
  { student_id: 1, phoneme_id: 36},
  { student_id: 1, phoneme_id: 37},
  { student_id: 1, phoneme_id: 38},
  { student_id: 1, phoneme_id: 39},
  { student_id: 1, phoneme_id: 40},
  { student_id: 1, phoneme_id: 41},
  { student_id: 1, phoneme_id: 42},
  { student_id: 1, phoneme_id: 43},
  { student_id: 1, phoneme_id: 44},
  { student_id: 1, phoneme_id: 45},
  { student_id: 1, phoneme_id: 46},
  { student_id: 1, phoneme_id: 47},
  { student_id: 1, phoneme_id: 48},
])